### ISSUE TITLE
Should we check file name to ensure license only added for Readme?

### ISSUE THREAD

**Issue by niftylettuce** [remarkjs/remark-license#11]
Otherwise it gets added to everything, even licenses themselves if they're `LICENSE.md`.

It'd be pretty messy to have to configure this otherwise to not do this.

What do you think @wooorm?

**Comment by niftylettuce** [comment]
I'm submitting a PR now that ignores license files.  That seems like best case right now at least.

**Comment by niftylettuce** [comment]
Done

**Comment by wooorm** [comment]
Seems good to me to ignore adding it to the license file themselves: You can use the `LICENSE` regex for that maybe?

All other files should be kind-of safe: they probably won’t have a `## License` header?

P.S. Seems you didn’t create PRs, but instead pushed everything to your master branch?

**Comment by niftylettuce** [comment]
> Seems good to me to ignore adding it to the license file themselves: You can use the LICENSE regex for that maybe?

No need - we only need to check the stem if it's LICENSE, LICENSE.txt, LICENSE.md, license.md, LIcense.md -- whatever -- I convert to lowercase and check if it `=== "license"`.  If there's some other reason we'd need that regex let me know.

> All other files should be kind-of safe: they probably won’t have a ## License header?

I think it gets automatically added for some reason, regardless?  Might be a bug - can you test it on your end too?  Even without a `## License` header it still did it in my `LICENSE.md` file for some reason (before this commit obviously)

> P.S. Seems you didn’t create PRs, but instead pushed everything to your master branch?

Yeah just pushed it all to master branch, was simpler + faster, if you really need me to separate I can, just let me know.

**Comment by wooorm** [comment]
> No need - we only need to check the stem if it's LICENSE, LICENSE.txt, LICENSE.md, license.md, LIcense.md -- whatever -- I convert to lowercase and check if it === "license". If there's some other reason we'd need that regex let me know.

Should check for both `license` and `licence`! Apparently, both are in use.

> I think it gets automatically added for some reason, regardless? Might be a bug - can you test it on your end too? Even without a ## License header it still did it in my LICENSE.md file for some reason (before this commit obviously)

I don’t think there’s code here to auto-add the `## License` header? 🤔 It isn’t in `mdast-util-heading-range` either...

> Yeah just pushed it all to master branch, was simpler + faster, if you really need me to separate I can, just let me know.

Yes, please. I like commits on the master branch that do one thing well, with a corresponding PR and possibly an issue! OK? 🎉

**Comment by niftylettuce** [comment]
Pushed commit for license regex support.  I don't have time to make a ton of different PR's right now - can this all just be merged? I kept my commits fairly organized.

**Comment by wooorm** [comment]
@niftylettuce I patched this change slightly differently: https://github.com/remarkjs/remark-license/commit/30713cb7f98a28c79aea461105056fdc955a2afa
