### ISSUE TITLE
Add `heading` option to match custom headings

### ISSUE THREAD

**Issue by nnmrts** [remarkjs/remark-license#12]
### Subject of the feature

Add a simple `match` option, so one can match any other heading than the english word "license" or "licence".

### Problem

Currently you can't use `remark-license` on multilingual (or just any other language than english) readmes. This would fix it, but probably other use cases exist as well. For example, one could prefer a heading like "License Information" or "Licensing".

### Expected behavior

The regular expression passed to this option should determine the heading under which `remark-license` generates the license info.

### Alternatives

The only alternative solution to this would be to use your own plugin, which is what I considered at first. But I think this can't be a just a "me-issue".

**Comment by wooorm** [comment]
[Released](https://github.com/remarkjs/remark-license/releases/tag/5.2.0)!
