### ISSUE TITLE
Definitions at end of section should be excluded

### ISSUE THREAD

**Issue by niftylettuce** [remarkjs/remark-license#7]
If you have the following:

```md
## License

[npm]: http://npmjs.org
```

Upon running `remark` with `remark-license` plugin it will strip the link `[npm]` etc

**Comment by wooorm** [comment]
Correct! It's not very pretty.

This plugin uses <https://github.com/syntax-tree/mdast-util-heading-range>, so the definitions are passed in 'nodes', and to make them persist you can add them to the returned nodes.

I think it makes the most sense to actually, optionally, let heading-range do this.

What do you think?

**Comment by niftylettuce** [comment]
This package conflicts though with your own preset.

I get tons of these warnings now:

```log
  93:1-93:30  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
    95:1-95:34  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
    97:1-97:37  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
    99:1-99:27  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  101:1-101:41  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  103:1-103:49  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  105:1-105:36  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  107:1-107:40  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  109:1-109:43  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  111:1-111:41  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  113:1-113:71  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  115:1-115:52  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  117:1-117:41  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  119:1-119:30  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  121:1-121:40  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
  123:1-123:36  warning  Move definitions to the end of the file (after the node at line `171`)  final-definition            remark-lint
```

**Comment by wooorm** [comment]
I know, I don't use it personally.
Plus that's not a reply to my above comment 😛

**Comment by niftylettuce** [comment]
I was confused by the comment* so much hahahaha

**Comment by niftylettuce** [comment]
@wooorm Since this plugin formats it to just a single line / node, shouldn't we only check for the next two immediate lines?

**Comment by niftylettuce** [comment]
@wooorm How can we implement this?  I'm trying to read through the docs now and understand `Compiler` - looking at headings gap plugin and experimenting.

**Comment by wooorm** [comment]
No, I don‘t think we can just check one node. This feature would benefit other plugins too.

First, have you read up on what [`mdast-util-heading-range`](https://github.com/syntax-tree/mdast-util-heading-range) does?

In essence: it searches for a section, and gives you its first node (a heading), the content in the section, and the end node (another heading, or nothing if it it’s not there).

I think we should change that, optionally, by looking at `end` and then walking back, and moving all those definitions “outside” the section.

E.g., say you have the following:

```markdown
# License

Paragraph

[definition-a]: example.com

[definition-b]: example.com
```

Proposed: `Paragraph` would be in `nodes`, `definition-a` would be `end`.
Currently: `Paragraph`, `definition-a`, `definition-b` are in `nodes`, there’s no `end`.

**Comment by niftylettuce** [comment]
Reading up on it now - this explanation you made makes sense 👌

**Comment by niftylettuce** [comment]
I don't think I'd be able to do this efficiently, I just did write a major plugin enhancement though over at <https://github.com/hughsk/remark-contributors/pull/4>, so that taught me a lot about `remark` and `retext` so far.

**Comment by wooorm** [comment]
Done! https://github.com/syntax-tree/mdast-util-heading-range/commit/9ec55003cfed8667128476c19a715038f1a0d7cb

**Comment by niftylettuce** [comment]
Can you add to this package and version bump? @wooorm

**Comment by wooorm** [comment]
Could you create the loose PRs first? That way my changes won’t conflict yours. I’ll update it here after that.
